# Webscrapping

## 2. Selenium - Craft Co

### 2.1. Extract Company (Name) Column For Further Webscraping

In [64]:
# !pip install selenium

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException
from time import sleep

import pandas as pd
import dbm

In [65]:
#import file
cleaned_reddit_df = pd.read_csv('./beautifulsoup_reddit_data_cleaned.csv')
cleaned_reddit_df.head()

,Company Abbreviation,Company Name,Stock Exchange,Users,Comments,Posts,Price,Price Change,Price Change in the last 24h,Volume,Market Cap
0,TSLA,"Tesla, Inc.",NASDAQ,489,936.0,57,$ 762.32,+60.34 (+8.59%),+52.82%,44M,$ 731.72B
1,SPY,SPDR S&P 500 ETF Trust,NYSE,471,818.0,30,$ 412.86,+1.22 (+0.29%),-4.52%,54M,NaN
2,AAPL,Apple Inc.,NASDAQ,258,485.0,29,$ 134.43,+3.19 (+2.43%),-0.34%,91M,$ 2.26T
3,AMD,"Advanced Micro Devices, Inc.",NASDAQ,264,454.0,23,$ 80.19,+1.61 (+2.04%),-39.22%,38M,$ 97.4B
4,APHA,Aphria Inc.,NASDAQ,245,423.0,19,$ 14.85,+0.90 (+6.45%),-26.82%,20M,$ 4.7B

In [66]:
company_df = cleaned_reddit_df["Company Name"]
company_list = company_df.values.tolist()
print(company_list)

['Tesla, Inc.', 'SPDR S&P 500 ETF Trust', 'Apple Inc.', 'Advanced Micro Devices, Inc.', 'Aphria Inc.', 'AMC Entertainment Holdings, Inc.', 'NVIDIA Corporation', 'Alibaba Group Holding Limited', 'GameStop Corp.', 'Johnson & Johnson', 'Cloudflare, Inc.', 'Roblox Corporation', 'Vanguard S&P 500 ETF', 'iShares Global Clean Energy ETF', 'Invesco QQQ Trust', 'Palantir Technologies Inc.']

### 2.2 Craft Co (Competitors)

In [68]:
competitor_list = []

for company in company_list:
    driver = webdriver.Chrome('./chromedriver.exe') #need to download chromedriver into the same file 
    driver.get("https://craft.co/")
    elem = driver.find_element_by_name("q")
    elem.clear()
    sleep(3)
    elem.send_keys(company)
    sleep(3)
    
    elem.send_keys(Keys.RETURN)

    apply_button = WebDriverWait(driver, 100).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="app"]/div/div[2]/div/div[2]/ul/li[1]/a[2]')))
    apply_button.click() 
    sleep(3)

    competitor_button = WebDriverWait(driver, 100).until(EC.presence_of_element_located((By.LINK_TEXT, 'Competitors')))
    competitor_button.click()      
    sleep(3)

    competitors = WebDriverWait(driver,100).until(EC.presence_of_element_located((By.CLASS_NAME, 'compare-companies__chips')))
    competitors_name = competitors.text
    competitor_list.append(competitors_name)
    sleep(3)
    
    driver.quit()
    
print(competitor_list)

['Tesla\nMTA\nMicroelettrica Scientifica\nDynapower\nMelchioni', 'S & S Diesel\nSuperpar Otomotiv\nCarter Fuel Systems\nDrake\nSimpsons', 'Apple\nHP\nIBM\nToshiba\nAcer\nHewlett Packard Enterprise\nLenovo\nHuawei\nMicrosoft\nSamsung Electronics\nDell Technologies\nSony', 'Micro Interventional Devices\nNipro Medical\nArthrex\nConvaTec\nAlcon', 'Aphria\nCronos Group\nAurora\nCanopy Growth\nOrganigram', 'AMC Entertainment\nCineplex\nCinemark\nRegal Entertainment Group\nMarcus Corporation\nAlamo Drafthouse', 'NVIDIA\nInfor\nBroadcom\nXilinx\nAMD\nIntel\nQualcomm', 'Alibaba\nQurate Retail Group\nCoupang\nASOS\nJD.com\nWalmart\nBest Buy\nAmazon', 'Gamestop\nAuchan\nCarrefour\nSony\nMicrosoft\nBest Buy\nAmazon\nNintendo', 'Johnson\nGMW Associates\nSistemes Electronics Progres\nDJB Instruments\nMarlin Manufacturing', 'CloudFlare\nNGINX\nLimelight Networks\nN7 - The Nitrogen Platform\nDyn\nAkamai\nImperva\nZscaler', 'Roblox\nFlowPlay\nEpic Games\nUnity Technologies\nMojang', 'Vanguard\nEdward Jones\nMerrill Lynch\nFranklin Templeton\nFidelity Investments\nBlackRock\nTIAA', 'iShares\nUfg Wealth Management\nCynex\nProfessional Investments\nSterling Mutuals', 'Invesco\nSchroders\nKarvy Private Wealth\nSanlam Investments\nVNDirect', 'Palantir\nTyler Technologies\nVerint\nTableau Software\nSplunk\nMu Sigma\nCognizant']

In [69]:
#data clearning 
new_list = []

for competitor in competitor_list:
    cleaned_competitor = competitor.replace('\n',',')
    new_list.append(cleaned_competitor)

print(new_list)

['Tesla,MTA,Microelettrica Scientifica,Dynapower,Melchioni', 'S & S Diesel,Superpar Otomotiv,Carter Fuel Systems,Drake,Simpsons', 'Apple,HP,IBM,Toshiba,Acer,Hewlett Packard Enterprise,Lenovo,Huawei,Microsoft,Samsung Electronics,Dell Technologies,Sony', 'Micro Interventional Devices,Nipro Medical,Arthrex,ConvaTec,Alcon', 'Aphria,Cronos Group,Aurora,Canopy Growth,Organigram', 'AMC Entertainment,Cineplex,Cinemark,Regal Entertainment Group,Marcus Corporation,Alamo Drafthouse', 'NVIDIA,Infor,Broadcom,Xilinx,AMD,Intel,Qualcomm', 'Alibaba,Qurate Retail Group,Coupang,ASOS,JD.com,Walmart,Best Buy,Amazon', 'Gamestop,Auchan,Carrefour,Sony,Microsoft,Best Buy,Amazon,Nintendo', 'Johnson,GMW Associates,Sistemes Electronics Progres,DJB Instruments,Marlin Manufacturing', 'CloudFlare,NGINX,Limelight Networks,N7 - The Nitrogen Platform,Dyn,Akamai,Imperva,Zscaler', 'Roblox,FlowPlay,Epic Games,Unity Technologies,Mojang', 'Vanguard,Edward Jones,Merrill Lynch,Franklin Templeton,Fidelity Investments,BlackRock,TIAA', 'iShares,Ufg Wealth Management,Cynex,Professional Investments,Sterling Mutuals', 'Invesco,Schroders,Karvy Private Wealth,Sanlam Investments,VNDirect', 'Palantir,Tyler Technologies,Verint,Tableau Software,Splunk,Mu Sigma,Cognizant']

In [74]:
#store list of competitors into dataframe
df_craftco_competitors = pd.DataFrame(new_list)

#show dataframe
df_craftco_competitors.head()

                                                   0
0  Tesla,MTA,Microelettrica Scientifica,Dynapower...
1  S & S Diesel,Superpar Otomotiv,Carter Fuel Sys...
2  Apple,HP,IBM,Toshiba,Acer,Hewlett Packard Ente...
3  Micro Interventional Devices,Nipro Medical,Art...
4  Aphria,Cronos Group,Aurora,Canopy Growth,Organ...

In [75]:
#split companies and their competitors into different columns
df_craftco_competitors_split = df_craftco_competitors.join(df_craftco_competitors[0].str.split(',', expand=True).add_prefix('competitor'))
df_craftco_competitors_split.head()

,0,competitor0,competitor1,competitor2,competitor3,competitor4,competitor5,competitor6,competitor7,competitor8,competitor9,competitor10,competitor11
0,"Tesla,MTA,Microelettrica Scientifica,Dynapower...",Tesla,MTA,Microelettrica Scientifica,Dynapower,Melchioni,None,None,None,None,None,None,None
1,"S & S Diesel,Superpar Otomotiv,Carter Fuel Sys...",S & S Diesel,Superpar Otomotiv,Carter Fuel Systems,Drake,Simpsons,None,None,None,None,None,None,None
2,"Apple,HP,IBM,Toshiba,Acer,Hewlett Packard Ente...",Apple,HP,IBM,Toshiba,Acer,Hewlett Packard Enterprise,Lenovo,Huawei,Microsoft,Samsung Electronics,Dell Technologies,Sony
3,"Micro Interventional Devices,Nipro Medical,Art...",Micro Interventional Devices,Nipro Medical,Arthrex,ConvaTec,Alcon,None,None,None,None,None,None,None
4,"Aphria,Cronos Group,Aurora,Canopy Growth,Organ...",Aphria,Cronos Group,Aurora,Canopy Growth,Organigram,None,None,None,None,None,None,None

In [78]:
#rename competitor0 as company
df_craftco_competitors_split.rename(columns={ df_craftco_competitors_split.columns[1]: "company" }, inplace = True)

#drop the redundant column
df_craftco_competitors_split = df_craftco_competitors_split.iloc[: , 1:]

#show dataframe
df_craftco_competitors_split.head()

,company,competitor1,competitor2,competitor3,competitor4,competitor5,competitor6,competitor7,competitor8,competitor9,competitor10,competitor11
0,Tesla,MTA,Microelettrica Scientifica,Dynapower,Melchioni,None,None,None,None,None,None,None
1,S & S Diesel,Superpar Otomotiv,Carter Fuel Systems,Drake,Simpsons,None,None,None,None,None,None,None
2,Apple,HP,IBM,Toshiba,Acer,Hewlett Packard Enterprise,Lenovo,Huawei,Microsoft,Samsung Electronics,Dell Technologies,Sony
3,Micro Interventional Devices,Nipro Medical,Arthrex,ConvaTec,Alcon,None,None,None,None,None,None,None
4,Aphria,Cronos Group,Aurora,Canopy Growth,Organigram,None,None,None,None,None,None,None

In [83]:
#save dataframe into csv file
df_craftco_competitors_split.to_csv('./selenium_competitors_data_cleaned.csv', sep=',', index = False) # Use Tab to separate